version: '3.8'

services:
  # PostgreSQL
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Oracle Database Express Edition (XE)
  oracle:
    image: gvenzl/oracle-xe
    environment:
      ORACLE_PASSWORD: Oradoc_db1
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  postgres-data:
  oracle-data: