name: Playwright CI with Slack Notification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22' # Ensure the correct Node.js version for your project

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: |
        mkdir -p test-results
        DEBUG=pw:api npx playwright test tests/e-commerce --reporter=playwright-ctrf-json-reporter,html
      env:
        CI: true

    - name: Debug test report
      run: cat ctrf/ctrf-report.json

    - name: Parse test results
      id: test-results
      run: |
        echo "Parsing test results..."
        TOTAL_TESTS=$(jq '.results.summary.tests' ctrf/ctrf-report.json)
        PASSED_TESTS=$(jq '.results.summary.passed' ctrf/ctrf-report.json)
        FAILED_TESTS=$(jq '.results.summary.failed' ctrf/ctrf-report.json)
        DURATION=$(jq '.results.summary.stop - .results.summary.start' ctrf/ctrf-report.json)

        # Convert duration from milliseconds to hours and minutes
        DURATION_HOURS=$((DURATION_MS / 3600000))
        DURATION_MINUTES=$(( (DURATION_MS % 3600000) / 60000 ))

        # Format the duration string
        DURATION="${DURATION_HOURS} hr ${DURATION_MINUTES} min"

        echo "TOTAL_TESTS=$TOTAL_TESTS" >> $GITHUB_ENV
        echo "PASSED_TESTS=$PASSED_TESTS" >> $GITHUB_ENV
        echo "FAILED_TESTS=$FAILED_TESTS" >> $GITHUB_ENV
        echo "DURATION=$DURATION" >> $GITHUB_ENV

        echo "TOTAL_TESTS: $TOTAL_TESTS"
        echo "PASSED_TESTS: $PASSED_TESTS"
        echo "FAILED_TESTS: $FAILED_TESTS"
        echo "DURATION: $DURATION"
      env:
        CI: true

    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: playwright-report/**/*

    - name: Notify Slack
      run: |
        REPORT_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

        curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\": \"Playwright Test Results\",
            \"attachments\": [
              {
                \"color\": \"#36a64f\",
                \"fields\": [
                  { \"title\": \"Total Tests\", \"value\": \"$TOTAL_TESTS\", \"short\": true },
                  { \"title\": \"Passed\", \"value\": \"$PASSED_TESTS\", \"short\": true },
                  { \"title\": \"Failed\", \"value\": \"$FAILED_TESTS\", \"short\": true },
                  { \"title\": \"Duration\", \"value\": \"$DURATION ms\", \"short\": true },
                  { \"title\": \"Report\", \"value\": \"$REPORT_URL\", \"short\": false }
                ]
              }
            ]
          }" ${{ secrets.SLACK_WEBHOOK_URL }}