name: Playwright CI with Slack Notification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22' # Ensure the correct Node.js version for your project

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: |
        DEBUG=pw:api npx playwright test tests/e-commerce --reporter=json > test-report.json || true
      env:
        CI: true

    - name: Check test report
      run: cat test-report.json

    - name: Parse test results
      id: test-results
      run: |
        echo "Parsing test results..."
        TOTAL_TESTS=$(jq '.suites | map(.specs | map(.tests | length) | add) | add' test-report.json)
        PASSED_TESTS=$(jq '.suites | map(.specs | map(.tests | flatten | map(select(.results[].status=="passed")) | length) | add) | add' test-report.json)
        FAILED_TESTS=$(jq '.suites | map(.specs | map(.tests | flatten | map(select(.results[].status=="failed")) | length) | add) | add' test-report.json)
        DURATION=$(jq '.suites | map(.specs | map(.tests | flatten | map(.results[].duration) | add) | add) | add' test-report.json)

        echo "TOTAL_TESTS=$TOTAL_TESTS" >> $GITHUB_ENV
        echo "PASSED_TESTS=$PASSED_TESTS" >> $GITHUB_ENV
        echo "FAILED_TESTS=$FAILED_TESTS" >> $GITHUB_ENV
        echo "DURATION=$DURATION" >> $GITHUB_ENV
      env:
        CI: true

    - name: Notify Slack
      run: |
        curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "Playwright Test Results",
            "attachments": [
              {
                "color": "#36a64f",
                "fields": [
                  { "title": "Total Tests", "value": "$TOTAL_TESTS", "short": true },
                  { "title": "Passed", "value": "$PASSED_TESTS", "short": true },
                  { "title": "Failed", "value": "$FAILED_TESTS", "short": true },
                  { "title": "Duration", "value": "$DURATION ms", "short": true }
                ]
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
