name: Playwright CI with Slack Notification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22' # Ensure the correct Node.js version for your project

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: |
        mkdir -p test-results
        DEBUG=pw:api npx playwright test tests/e-commerce --reporter=json > test-results/test-report.json || true
      env:
        CI: true

    - name: Debug test report
      run: cat test-results/test-report.json

    - name: Parse test results
      id: test-results
      run: |
        echo "Parsing test results..."
        TOTAL_TESTS=$(jq '[.suites[].specs[].tests[]] | length' test-results/test-report.json)
        PASSED_TESTS=$(jq '[.suites[].specs[].tests[] | select(.results[].status == "passed")] | length' test-results/test-report.json)
        FAILED_TESTS=$(jq '[.suites[].specs[].tests[] | select(.results[].status == "failed")] | length' test-results/test-report.json)
        DURATION=$(jq '.stats.duration' test-results/test-report.json)

        echo "TOTAL_TESTS=$TOTAL_TESTS" >> $GITHUB_ENV
        echo "PASSED_TESTS=$PASSED_TESTS" >> $GITHUB_ENV
        echo "FAILED_TESTS=$FAILED_TESTS" >> $GITHUB_ENV
        echo "DURATION=$DURATION" >> $GITHUB_ENV

        echo "TOTAL_TESTS: $TOTAL_TESTS"
        echo "PASSED_TESTS: $PASSED_TESTS"
        echo "FAILED_TESTS: $FAILED_TESTS"
        echo "DURATION: $DURATION"
      env:
        CI: true

    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: playwright-report

    - name: Notify Slack
      run: |
        REPORT_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

        curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "Playwright Test Results",
            "attachments": [
              {
                "color": "#36a64f",
                "fields": [
                  { "title": "Total Tests", "value": "'$TOTAL_TESTS'", "short": true },
                  { "title": "Passed", "value": "'$PASSED_TESTS'", "short": true },
                  { "title": "Failed", "value": "'$FAILED_TESTS'", "short": true },
                  { "title": "Duration", "value": "'$DURATION ms'", "short": true },
                  { "title": "Report", "value": "'$REPORT_URL'", "short": false }
                ]
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}